const paragraphs: string[] = [
    "The quick brown fox jumps over the lazy dog near the riverbank every morning as the sun begins to rise. This daily ritual has become a familiar sight for the villagers who gather by the water to start their day. The fox, with its sleek fur glistening in the golden light, moves with a grace that captivates everyone who watches. Meanwhile, the dog stretches lazily and yawns before settling back into its comfortable spot under the old oak tree. The contrast between the two animals never fails to bring a smile to the faces of those who witness this charming scene unfold each and every day without exception. Nature has a wonderful way of reminding us to appreciate the simple moments that make life truly beautiful and meaningful beyond measure.",
    "Technology has transformed the way we communicate and share information across the globe in ways that previous generations could never have imagined possible. From instant messaging to video conferencing, we can now connect with anyone in the world within seconds, breaking down barriers of distance and time that once seemed insurmountable. Social media platforms have created entirely new forms of expression and community building that continue to evolve at a rapid pace. The speed at which information travels today means that news and ideas spread faster than ever before, shaping public opinion and driving social change on a massive scale. As we navigate this digital landscape, it becomes increasingly important to develop critical thinking skills and digital literacy to distinguish between reliable sources and misinformation in our daily lives.",
    "Reading books is one of the most rewarding habits a person can develop throughout their lifetime. It expands vocabulary, improves focus and concentration, and opens doors to new ideas and perspectives that fundamentally shape our understanding of the world around us. Whether you prefer fiction that transports you to imaginary realms or nonfiction that deepens your knowledge of real events and concepts, the act of reading engages your mind in ways that few other activities can match. Studies have shown that regular readers tend to have better memory retention, stronger analytical thinking abilities, and greater empathy for others. Libraries and bookstores remain vital community spaces where people of all ages and backgrounds come together to share their love of literature and the written word.",
    "The ocean covers more than seventy percent of the surface of our planet and remains one of the most mysterious and largely unexplored frontiers of scientific discovery. Beneath the waves lies a world teeming with life, from the smallest plankton to the largest whales, all interconnected in a complex web of ecosystems that sustain life on Earth. Marine biologists estimate that millions of species living in the deep sea have yet to be discovered, classified, and studied by researchers. The ocean also plays a crucial role in regulating our climate, absorbing vast amounts of carbon dioxide and distributing heat around the globe through powerful currents. Protecting this precious resource from pollution, overfishing, and climate change is one of the most important challenges facing humanity in the coming decades.",
    "Learning to type quickly and accurately is an essential skill in the modern workplace that can significantly boost your productivity and efficiency in countless professional settings. Whether you are writing emails, coding software, creating documents, or communicating with colleagues through messaging platforms, fast and accurate typing saves valuable time every single day. The journey from a beginner who hunts and pecks at the keyboard to a proficient touch typist requires dedication, consistent practice, and patience with yourself as you build muscle memory over weeks and months. Many experts recommend starting with proper finger placement on the home row and gradually increasing speed while maintaining accuracy as the foundation of good typing technique. The investment of time and effort in developing this skill pays dividends throughout your entire career.",
    "Music has the extraordinary power to evoke deep emotions and bring people together across cultures, languages, and generations in ways that transcend ordinary communication. A single melody can remind us of cherished memories from our past, inspire us to overcome the challenges we face in the present, or fill us with hope for what the future might hold. From classical symphonies to modern pop songs, from traditional folk tunes to experimental electronic compositions, the diversity of musical expression reflects the incredible range of human creativity and experience. Learning to play an instrument or sing develops discipline, enhances cognitive abilities, and provides a lifelong source of joy and personal fulfillment. Throughout history, music has been an integral part of every known human civilization and continues to shape our collective identity today.",
    "The importance of regular exercise cannot be overstated when it comes to maintaining both physical and mental well being throughout every stage of life. Physical activity strengthens the heart and cardiovascular system, improves mental health by reducing symptoms of anxiety and depression, boosts energy levels, and helps maintain a healthy weight. Even moderate exercise such as a thirty minute walk each day can have profound benefits for your overall health and quality of life. Research consistently shows that active individuals tend to live longer, experience fewer chronic diseases, and report higher levels of life satisfaction compared to their sedentary counterparts. Finding an exercise routine that you genuinely enjoy is the key to making physical activity a sustainable and rewarding part of your daily lifestyle rather than a chore you dread.",
    "Coffee is one of the most popular beverages in the world, enjoyed by hundreds of millions of people each morning as part of their daily routine. Its rich aroma and bold flavor make it the perfect companion for starting a productive day, fueling conversations with friends, or simply savoring a quiet moment of solitude. The journey of coffee from bean to cup is a fascinating process that spans continents and involves countless skilled workers, from the farmers who cultivate the plants in tropical regions to the roasters and baristas who transform raw beans into the delicious drink we know and love. Different brewing methods, roast levels, and bean varieties create an astonishing range of flavors and experiences that coffee enthusiasts spend years exploring and appreciating in their pursuit of the perfect cup.",
    "Space exploration continues to push the boundaries of human knowledge and technological capability with every new mission launched beyond our atmosphere. From the first tentative steps on the moon to the ambitious plans for crewed missions to Mars, humanity has always been driven by an insatiable curiosity about what lies beyond our home planet. Robotic probes have visited every planet in our solar system, revealing breathtaking landscapes and surprising discoveries that challenge our understanding of planetary science and the potential for life elsewhere in the universe. The development of reusable rockets and commercial space flights is making access to space more affordable and accessible than ever before. Each discovery we make among the stars teaches us more about our own origins and inspires the next generation of scientists and explorers.",
    "Cooking at home allows you to take full control of the ingredients, portions, and nutritional quality of the meals you consume on a daily basis. It is a deeply creative outlet that can also save significant amounts of money compared to eating out at restaurants or ordering takeout food regularly. The process of selecting fresh ingredients, following or improvising recipes, and transforming raw materials into delicious dishes is both satisfying and empowering for people of all skill levels. Sharing home cooked meals brings families and friends together around the dinner table, fostering meaningful connections and creating lasting memories that extend far beyond the food itself. Learning to cook well is a life skill that pays dividends in terms of health, happiness, and financial well being throughout your entire adult life.",
    "The art of photography captures moments in time that would otherwise be lost forever to the relentless passage of days, months, and years. A single photograph has the power to tell a compelling story, convey raw and powerful emotion, and preserve important pieces of history for future generations to study, appreciate, and learn from. The evolution of photography from bulky film cameras to sophisticated digital sensors and smartphone lenses has democratized the medium, allowing virtually anyone to document their world with remarkable clarity and artistic expression. Understanding concepts like composition, lighting, exposure, and timing separates truly great photographs from ordinary snapshots and elevates photography from a casual hobby to a genuine art form. Whether capturing sweeping landscapes or intimate portraits, photographers serve as visual storytellers for our shared human experience.",
    "Climate change is one of the most pressing and complex issues facing humanity in the twenty first century and demands urgent collective action from every corner of the globe. Rising global temperatures, melting ice caps and glaciers, rising sea levels, and increasingly frequent extreme weather events are already affecting communities and ecosystems worldwide in profound and often devastating ways. Scientists have reached an overwhelming consensus that human activities, particularly the burning of fossil fuels and deforestation, are the primary drivers of these changes to our planetary climate system. Transitioning to renewable energy sources, improving energy efficiency, protecting and restoring natural carbon sinks, and adopting more sustainable practices in agriculture, transportation, and industry are all essential steps toward mitigating the worst impacts of climate change for current and future generations.",
    "Writing is a fundamental skill that enables the clear and effective communication of complex ideas across time and distance in ways that spoken language alone cannot achieve. Whether you are crafting an engaging story, composing a professional email, drafting an important business report, or expressing your personal thoughts in a journal, the ability to write well opens countless doors in both your personal and professional life. Good writing requires not only a solid command of grammar and vocabulary but also the ability to organize thoughts logically, anticipate the needs and expectations of your audience, and revise your work with a critical eye for clarity and precision. The best writers understand that writing is a process of discovery and refinement that improves with consistent practice and a willingness to learn from feedback.",
    "Artificial intelligence is rapidly and fundamentally changing industries ranging from healthcare and finance to transportation and creative arts in ways that are both exciting and challenging for society as a whole. Machine learning algorithms can now diagnose certain diseases with accuracy that matches or exceeds human specialists, drive vehicles through complex urban environments, compose music, generate realistic images, and even write coherent text based on simple prompts. These remarkable capabilities raise important questions about the future of work, privacy, intellectual property, and the ethical boundaries of technology that we as a society must thoughtfully address. As AI systems become more powerful and pervasive, developing robust frameworks for responsible development and deployment becomes increasingly critical to ensure these tools benefit humanity broadly rather than concentrating power in the hands of a few.",
    "Gardens provide a peaceful and restorative retreat from the hustle and bustle of modern daily life, offering a sanctuary where people can reconnect with nature and find a sense of calm and balance. Tending to plants, flowers, vegetables, and herbs can significantly reduce stress levels, improve mood and mental well being, and create a beautiful outdoor space for relaxation, reflection, and quiet contemplation. The practice of gardening also teaches valuable lessons about patience, responsibility, and the natural cycles of growth and renewal that govern all living things on our planet. Whether you have a sprawling backyard or a few pots on a small balcony, cultivating a garden connects you to the earth and provides the deep satisfaction of nurturing something from a tiny seed into a thriving living organism that brings joy to all who experience it.",
    "The history of cinema spans over a century of remarkable innovation, artistic expression, and cultural influence that has fundamentally shaped how we tell stories and understand the world around us. From the earliest silent films that amazed audiences with moving images to modern blockbusters featuring breathtaking visual effects and immersive sound design, movies have evolved into one of the most powerful and influential forms of entertainment and communication worldwide. Great films have the ability to transport viewers to different times and places, challenge their assumptions, provoke thought and discussion, and elicit a full spectrum of human emotions from joy and laughter to sorrow and contemplation. The collaborative nature of filmmaking brings together writers, directors, actors, cinematographers, editors, and countless other talented professionals to create a unified artistic vision.",
    "Teamwork is essential for achieving ambitious goals that no single individual could accomplish alone, regardless of their talent, intelligence, or determination. Effective collaboration requires a foundation of mutual trust, open and honest communication, clearly defined roles and responsibilities, and a shared vision that motivates every member of the group to contribute their best effort toward the common objective. The most successful teams harness the diverse strengths, perspectives, and experiences of their individual members to generate creative solutions and overcome obstacles that would stymie any one person working in isolation. Building strong team dynamics takes time, intention, and a willingness to navigate disagreements constructively while maintaining respect for every voice at the table. Organizations that invest in developing a culture of genuine teamwork consistently outperform those that rely solely on individual achievement.",
    "Mountains have always fascinated explorers, adventurers, and dreamers seeking to test the outer limits of human endurance, courage, and determination against the raw and indifferent power of nature. The challenge of reaching a remote summit demands extraordinary physical fitness, unwavering mental strength, meticulous preparation, and a deep respect for the unpredictable and often dangerous conditions that high altitude environments present to those who dare to climb. From the towering peaks of the Himalayas to the rugged ridges of the Andes and Alps, mountain landscapes offer some of the most spectacular and awe inspiring scenery on Earth. The mountaineering community is built on traditions of mutual support, careful risk assessment, and environmental stewardship that reflect the values of those who are drawn to these majestic natural formations that have inspired humanity for countless generations.",
    "Sleep is absolutely crucial for maintaining good health, strong cognitive function, emotional resilience, and overall well being throughout every stage of human life from infancy to old age. During sleep, the body performs essential repair and maintenance processes, the brain consolidates memories and processes the experiences of the day, and the immune system strengthens its defenses against illness and infection. Despite the overwhelming scientific evidence supporting the importance of adequate sleep, many people in modern society chronically deprive themselves of the rest they need due to demanding work schedules, digital distractions, stress, and poor sleep habits. Establishing a consistent sleep routine, creating a comfortable and dark sleeping environment, limiting screen time before bed, and managing caffeine intake are all proven strategies for improving sleep quality and duration.",
    "The internet has revolutionized education by making vast repositories of knowledge and learning opportunities accessible to anyone with a connection, regardless of their geographic location, socioeconomic status, or age. Online courses, interactive tutorials, educational videos, digital libraries, and collaborative learning platforms have democratized access to information and created unprecedented opportunities for people everywhere to develop new skills, pursue their passions, and advance their careers. Students can now learn from world class instructors and institutions without leaving their homes, access materials in multiple languages and formats, and connect with fellow learners from diverse backgrounds and cultures around the globe. This transformation of education has also challenged traditional institutions to innovate, adapt their teaching methods, and find new ways to provide value in an increasingly digital and interconnected world.",
    "Architecture shapes the physical spaces where we live, work, gather, worship, and play, profoundly influencing our daily experiences, social interactions, and psychological well being in ways that we often take for granted. Great buildings and urban designs combine functional efficiency with aesthetic beauty, reflecting the values, aspirations, technological capabilities, and cultural identity of the societies that create them across different eras and regions of the world. From ancient temples and medieval cathedrals to gleaming modern skyscrapers and sustainable green buildings, the evolution of architectural design tells the story of human civilization itself. Contemporary architects face the exciting challenge of creating structures that are not only visually striking and functionally excellent but also environmentally sustainable, energy efficient, and resilient to the growing impacts of climate change and natural disasters.",
    "Volunteering is a deeply rewarding way to give back to your community while simultaneously developing valuable new skills, expanding your professional network, and gaining meaningful life experiences that enrich your personal growth. Helping others through volunteer work fosters empathy, builds genuine human connections across social and cultural boundaries, and creates a powerful sense of purpose and fulfillment that material success alone cannot provide. Whether you choose to mentor young people, assist at a local food bank, participate in environmental cleanup efforts, support elderly neighbors, or contribute your professional skills to nonprofit organizations, there are countless ways to make a meaningful positive difference in the lives of those around you. Studies consistently show that people who volunteer regularly report higher levels of happiness, better physical health, and a stronger sense of belonging to their community.",
    "The study of languages reveals fascinating and complex patterns in how human beings think, communicate, form social bonds, and construct their understanding of reality across different cultures and historical periods. Every language offers a unique window into the worldview, values, traditions, and cognitive frameworks of a particular culture, subtly shaping the way its speakers perceive, categorize, and interact with the world around them in ways that are often invisible until examined closely. Learning a new language is not merely an exercise in memorizing vocabulary and grammar rules but a transformative journey that expands your capacity for empathy, creative thinking, and cross cultural understanding. Bilingual and multilingual individuals often demonstrate enhanced cognitive flexibility, improved problem solving abilities, and greater cultural sensitivity that serve them well in both personal relationships and professional environments.",
    "Innovation drives progress in every field of human endeavor, from science, medicine, and engineering to art, entertainment, and social organization, serving as the engine that propels civilization forward through the ages. The willingness to experiment boldly, embrace failure as a learning opportunity, question established assumptions, and persistently try again in the face of setbacks is what separates truly breakthrough discoveries and inventions from merely incremental improvements to existing systems and processes. Throughout history, the most transformative innovations have often come from unexpected sources, arising at the intersection of different disciplines, cultures, and ways of thinking that combine to produce something genuinely new and valuable. Fostering a culture of innovation requires creating environments where curiosity is encouraged, diverse perspectives are welcomed, calculated risks are supported, and creative collaboration is valued and rewarded.",
    "Forests are vital ecosystems that support an extraordinary level of biodiversity and play an essential role in regulating the global climate, water cycles, and atmospheric composition that sustain life on Earth as we know it. They provide clean air by absorbing carbon dioxide and releasing oxygen, filter fresh water through their root systems, prevent soil erosion on hillsides and riverbanks, and offer irreplaceable habitat for countless species of plants, animals, fungi, and microorganisms. Old growth forests in particular serve as massive carbon sinks that help mitigate the effects of climate change by storing billions of tons of carbon in their trunks, branches, roots, and soil over centuries of growth. Despite their immense ecological importance, forests around the world continue to face serious threats from deforestation, illegal logging, agricultural expansion, and the growing impacts of rising temperatures.",
    "Digital privacy has become a major concern for individuals and organizations alike as more of our personal information, financial transactions, social interactions, and daily activities move into online spaces that are vulnerable to surveillance, data collection, and potential misuse. Understanding how to protect your sensitive data, maintain meaningful control over your digital footprint, and navigate the complex landscape of privacy policies and security settings is an essential skill for everyone living in today's increasingly connected and data driven world. Major data breaches affecting millions of users have demonstrated the risks of entrusting personal information to organizations that may not adequately protect it from unauthorized access by hackers, advertisers, or government agencies. Taking proactive steps such as using strong unique passwords, enabling two factor authentication, being selective about what you share online, and regularly reviewing your privacy settings can significantly reduce your exposure."
];

export function getRandomParagraph(): string {
    return paragraphs[Math.floor(Math.random() * paragraphs.length)];
}

/**
 * Generate a continuous block of text that is at least `minChars` long
 * by concatenating randomly-ordered paragraphs.
 */
export function getRandomText(minChars: number): string {
    const shuffled = [...paragraphs].sort(() => Math.random() - 0.5);
    let result = "";
    let idx = 0;
    while (result.length < minChars) {
        result += (result ? " " : "") + shuffled[idx % shuffled.length];
        idx++;
        // Re-shuffle after exhausting all paragraphs
        if (idx % shuffled.length === 0) {
            shuffled.sort(() => Math.random() - 0.5);
        }
    }
    return result;
}
